# Conclusion

<p>
  <br>
While working on the Unicorn and failed startup datasets, we came across various types of concepts from missing value imputation to using interactive plotting strategies.
From the above exploratory data analysis and visualizations, we infer that initial funding is a major requirement for a company’s growth and this depends on the investment of ideas within the company. In a startup culture, the objective is to enhance innovative strategies to tackle global problems. This objective can be achieved when the average funding received by the company in various seeding rounds increase over-time, and which further leads to more number of investors investing in the company.
<br><br>
By exploring the datasets, we can conclude that there are a variety of reasons for a startup's success which is determined by the industry-specific conditions, the number of investing organizations, the initial funding received and the scope of the domain. 
The right combination of factors have a huge impact on the success of a startup; for example, a very low or a very high number of investors prove to be detrimental to the success of any given startup in a particular domain.

<br><br>
The startup’s growth is determined by the above factors which leads to the success or failure. The failure or success of a startup is directly related to adoption of constructive feedbacks and implementation of newer and enhanced technologies, and thus is dependant on amounts received in different funding rounds received by different investors.



</p>