--- 
title: "Startup Analysis"
author: "Varalika Mahajan and Vrinda Bhat"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Startups play a major role in the development of the economic growth of the country. They promote ideation, spur innovation and thereby generate employment strategies to make accentuated growth in the economy. There has been an exponential rise in the number of startups over the past few years. To be ahead of the competition, there is a necessity to predict the success of startups thereby allowing investors to find companies that have the potential for rapid growth.
<br>
<br>

<b> 1.1 Motivation </b>
<br>
Research study has recognized the importance of startups for economic dynamism and competition. The startup ecosystem is highly uncertain and its volatile nature makes it challenging to examine and understand data to determine if a firm will succeed. The time and computationally costly nature of this prediction problem necessitate the use of a quantified and visually understandable model, which allows for an objective approach to predicting startup success or not.

According to a recent New York Times piece, an unprecedented number of companies, easily 25 and probably exceeding 40, are now valued at $1 billion or more. That figure is expected to reach 100 in a year. As a result, a record number of entrepreneurs is going to be the future.
<br> <br>

<b> 1.2 Objective </b>
<br>
The project's goal is to forecast whether a currently existing startup will be a success or a failure. A company's success is defined based on various factors including a number of founders, investors, age of the company, funding round, acquisition, domain, and much more.
Our aim is to visualize all these factors across the leading unicorns like Uber, and Airbnb against the upcoming unicorns, DataBricks, and FTX and further see, what they did differently against the failed startups.