# Proposal

## Research topic

The cost of starting a business is at an all-time low. If we recall the time when developing an eCommerce website might easily cost a million dollars. Now, One can easily build a website for nearly nothing and get started with their latest invention or personal services.
<br> <br>
<b> Two facts arise- </b>
<br>
1. Startups are growing at an unexpectable rate.
<br>
2. 90% of startups fail.
<br> <br>
With this growth, there is a huge opportunity to analyze, “What are the reasons behind the success of a startup, and what leads to the downfall?”.
<br> <br>
The following are the key factors for the success of startups: Idea, Founding Team, Investors, category, city, age of the company, amount raised, and many more; being all factors equally relevant in the analysis. These factors have had a wide impact on subsequent research.
<br> <br>
Success factors have been linked to certain amounts of turnover, as well as to the dedication of the founders, their commercial capacity, the age of the company, the number of employees, the existence of promoter partners in the company, the technological skills of the promoter partners and the startup’s ability to exceed the break-even point.
<br> <br>
<b>2.1.1 Scope</b> <br>
This analysis  aims to shed light on this issue through the statistical analysis of a samples of startup data including that of former and current unicorns. Through a detailed study of the selected daatsets, but from the perspective of business experience, the scope is to identify the comparative relevance of those factors that recent research has highlighted as the main drivers of start-up success. Our analysis allows us to define a core of practical business success factors. This core makes it possible to identify the intersection between success in business practice and predicting the success of startups. In addition, some differences found between the geographic areas, suggest that financial and developmental characteristics influence the weight given to the various reasons for success, which further enhances the research in this area.



## Data availability
<b> Dataset 1: List of unicorn companies </b>
<br> <b> Link: </b> <a> https://www.cbinsights.com/research-unicorn-companies </a> <br>
<b> Source: </b> CBN Insights<br>
<b> Format of the dataset: </b> CSV<br>
<b> Description: </b> A unicorn company, or unicorn startup, is a private company with a valuation over $1 billion. As of October 2022, there are over 1,200 unicorns around the world. Popular former unicorns include Airbnb, Facebook and Google. Variants include a decacorn, valued at over $10 billion, and a hectocorn, valued at over $100 billion. The dataset consists of unicorn companies all over the globe, from various industries from software to e-Commerce. The dataset consists of current unicorns in the industry, with columns - Company, Valuation, Date joined, Country, City, Industry, and Investors. <br>
<br>
<table>
  <tr>
    <th>Column Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Company Name</td>
    <td>Name of the startup</td>
  </tr>
  <tr>
    <td>Valuation</td>
    <td>Company's net worth</td>
  </tr>
    <tr>
    <td>Date Joined</td>
    <td>Company's Unicorn establishment date</td>
  </tr>
  <tr>
    <td>Country</td>
    <td>Country of Startup</td>
  </tr>
    <tr>
    <td>City</td>
    <td>City of Startup</td>
  </tr>
  <tr>
    <td>Industry</td>
    <td>Domain of Startup</td>
  </tr>
    <tr>
    <td>Investors </td>
    <td>Investing members of the startup</td>
  </tr>
</table>

<br> <b> Dataset 2: List of startups </b>
<br> <b>Link: </b> <a> https://github.com/Kerenn/Cs210_StandupStartups/blob/master/AB.csv </a> <br>
<b> Source: </b> Github<br>
<b> Format of the dataset: </b> CSV<br>
<b>Description: </b>This dataset includes the best-funded growth startups, defined by the total amount raised in different rounds in various industries ranging from software to e-Commerce. The dataset consists of a list of startups, with the following columns - Company, Status(Operational or Exited), Amounts_raised_in_different_funding_rounds, Categories, YCombinatorYear, HeadquartersCity. <br>
<br>
<table>
  <tr>
    <th>Column Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Company Name</td>
    <td>Name of the startup</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>Company's operating status</td>
  </tr>
    <tr>
    <td>Amount raised</td>
    <td>Amount raised in different funding rounds</td>
  </tr>
  <tr>
    <td>Categories</td>
    <td>Domain of the startup</td>
  </tr>
    <tr>
    <td>YCombinator Year</td>
    <td> Founding Year </td>
  </tr>
  <tr>
    <td>Headquarters City</td>
    <td>City of the startup</td>
  </tr>
</table>

<br> <b> Dataset 3: List of startups </b>
<br> <b> Link: </b> <a> https://www.kaggle.com/datasets/siddarthareddyt/startup-analysis-dataset </a> <br>
<b> Source: </b> Kaggle<br>
<b>Format of the dataset: </b> CSV<br>
<b> Description: </b> The dataset consists of all companies in the categories of software, technology, and others combined. The dataset consists of a list of startups, with the following columns - Name, Category list, funding total in USD, Status, Country Code, State Code, City, Funding rounds, Investors and Number of investors. <br>
<b> Reasons to choose this dataset: </b> Theis dataset on Kaggle includes data of all startups in the USA having a unique column named ‘Status’ which shows the current status of the startup(operating/closed/acquired). In order to achieve a well rounded analysis, this dataset allows us to analyze the startups which became successful vs that shutdown and helps us to visualize the distribution effectively. <br>
<table>
  <tr>
    <th>Column Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Company Name</td>
    <td>Name of the startup</td>
  </tr>
  <tr>
    <td>Category List</td>
    <td>Domain of the startup</td>
  </tr>
    <tr>
    <td>Funding total in USD</td>
    <td>Amount raised in different funding rounds in USD</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>Status of the startup</td>
  </tr>
    <tr>
    <td>Country Code</td>
    <td>Code of the country</td>
  </tr>
  <tr>
    <td>State Code</td>
    <td>Code of the state</td>
  </tr>
    <tr>
    <td>City</td>
    <td>City of the startup</td>
  </tr>
    <tr>
    <td>Funding rounds</td>
    <td>Amount raised in different funding rounds</td>
  </tr>
    <tr>
    <td>Investors</td>
    <td>Investing companies</td>
  </tr>
    <tr>
    <td>Number of Investors</td>
    <td>Number of investing companies</td>
  </tr>
</table>
<br>

<b> 2.2.1 Task Analysis </b>
<br> <br>
<b> Step 1: Understanding the data we require </b> <br>
The startup dataset is analyzed and understood by determining context and its business alignment. <br> <br>

<b> Step 2: Data pre-processing </b> <br>
The categorical variables are identified and encoded before plotting or numerical variables, which can be normalized before analysis to give a better understanding of their impact. <br> <br>

<b> Step 3: Data cleansing </b> <br>
The irrelevant and missing parts in the dataset are noted and data transformation and reduction techniques are used to increase the storage efficiency and interpretability. <br> <br>

<b> Step 4: Exploratoratory Data Analysis </b> <br>
Step 4.1 Identify the relationship of all variables against each other <br>
Step 4.2 Identify strongly related variables <br>
Step 4.3 Identify features with more importance <br>
Step 4.4 Group variables and create plots to summarize their effect on the other <br> <br>

<b> Step 5: Inferential Statistical Modelling of the result </b> <br>
The statistical measures are noted down from the observed analysis to get clarity if our prediction is strongly supported by mathematical figures like mean, median, mode or percentile, quartiles. <br> <br>

<b> Step 6: Formulate the results and observations </b> <br>
The observations are formulated from each graph into stable inferences, which can be confidently reported after the analysis is conducted. <br> <br>

<b> Step 7: Communicate </b> <br>
A formal report is generated, stating our observations in detail and the learnings from the startup’s initial journey to analyze its future.
<br> <br>

<b> 2.2.2 Summary </b>
<br> <br>
<ul> <li> The first contribution of our study is a qualitative review of the entrepreneurial success of purpose-built startups - the success factors identified by corporate practices are analyzed. </li>
<br>

<li> The second contribution of our study is the set of qualitative findings related to entrepreneurial success factors. Starting from a set of factors, we analyze and explore the more relevant findings and the representative gaps between the factors. </li>
<br>

<li> The third contribution is to find additional factors which may impact the success of startups which are found by statistical analysis of the data.  </li> </ul>
<br>

In summary, we will identify the primary and secondary factors influencing startup growth. A start-up, as the term implies, is a new firm that is innovative. While the motivation to start a business is the most important aspect. There are other more aspects that can influence its success. Building the right team, the proper founding team, financing prospects, the age of the firm before launch, and many other criteria are all critical.
